import json
import time as _time

from flask import Blueprint, Response, abort, jsonify, request
from markupsafe import escape

from app import store
from app.ui import base_html

bp = Blueprint("report", __name__)


def _not_found_html(rid: str) -> str:
    body = f"""
<div class="card">
  <div class="card-title">report not found</div>
  <div class="empty-state">
    no report with id <code>{escape(rid)}</code> in the store<br><br>
    <a href="/" style="color: var(--accent); text-decoration: none;">← all reports</a>
  </div>
</div>
"""
    return base_html("404 — OpenSCAP Dashboard", body, active="index")


def _generate_bash(rules: list, report: dict) -> str:
    hostname = report.get('hostname', 'unknown')
    sep = '# ' + '=' * 72
    lines = [
        "#!/usr/bin/env bash",
        "#",
        "# OpenSCAP Remediation Script",
        f"# Host:    {hostname}",
        f"# Profile: {report.get('profile', '')}",
        f"# Date:    {report.get('scan_date', '')}",
        f"# Rules:   {len(rules)}",
        "#",
        "# Generated by OpenSCAP Dashboard",
        "#",
        "set -euo pipefail",
        "",
    ]
    for rule in rules:
        fix = (rule.get('fix_bash') or '').strip()
        lines += [
            sep,
            f"# {rule.get('title', rule['id'])[:72]}",
            f"# Severity: {rule.get('severity', 'unknown')}",
            f"# Rule:     {rule['id']}",
            sep,
        ]
        if fix:
            lines.append(fix)
        else:
            lines.append(
                "# ⚠  No automated bash remediation available"
                " — manual action required."
            )
        lines.append("")
    return "\n".join(lines)


def _generate_ansible(rules: list, report: dict) -> str:
    hostname = report.get('hostname', 'unknown')
    sep = '    # ' + '=' * 68
    lines = [
        "---",
        "# OpenSCAP Remediation Playbook",
        f"# Host:    {hostname}",
        f"# Profile: {report.get('profile', '')}",
        f"# Date:    {report.get('scan_date', '')}",
        f"# Rules:   {len(rules)}",
        "#",
        "# Generated by OpenSCAP Dashboard",
        "",
        f"- name: \"OpenSCAP Remediation — {hostname}\"",
        "  hosts: all",
        "  become: true",
        "  tasks:",
        "",
    ]
    for rule in rules:
        fix = (rule.get('fix_ansible') or '').strip()
        title = rule.get('title', rule['id'])
        lines += [sep, f"    # {title[:68]}", f"    # Severity: {rule.get('severity', 'unknown')} | {rule['id']}", sep]
        if fix:
            lines.append(f"    - name: \"Remediate: {title[:55]}\"")
            lines.append("      block:")
            for line in fix.split('\n'):
                lines.append(f"        {line}")
            lines.append("      rescue:")
            lines.append(f"        - name: \"Skipped (failed): {title[:52]}\"")
            lines.append("          ansible.builtin.debug:")
            lines.append("            msg: >-")
            lines.append(f"              Remediation skipped for rule '{rule['id']}'.")
            lines.append("              Failed task: {{ ansible_failed_task.name }}.")
            lines.append("              Error: {{ ansible_failed_result.msg | default('see logs') }}")
        else:
            lines += [
                f"    - name: \"MANUAL REMEDIATION: {title[:52]}\"",
                "      ansible.builtin.debug:",
                f"        msg: \"No automated fix — manually remediate: {rule['id']}\"",
            ]
        lines.append("")
    return "\n".join(lines)


def _report_html(r: dict) -> str:
    host = escape(r.get("hostname", "unknown"))
    date = escape(r.get("scan_date", "n/a"))
    profile = escape(r.get("profile", "") or "n/a")
    score = int(r.get("score", 0))
    source = escape(r.get("source", ""))
    loaded_at = escape(r.get("loaded_at", ""))
    filename = escape(r.get("filename", ""))
    report_id = r.get("id", "")

    results = r.get("results") or {}
    pass_n = results.get("pass", 0)
    fail_n = results.get("fail", 0)
    nc_n = (results.get("notchecked", 0) or 0) + (results.get("unknown", 0) or 0)
    na_n = results.get("notapplicable", 0)
    total = r.get("total", 0) or 1

    fail_total = r.get("fail_total", fail_n) or fail_n
    shown = len(r.get("rules") or [])
    trunc_notice = ""
    if fail_total > shown:
        trunc_notice = f'<div class="trunc-notice">Showing {shown} of {fail_total} failures</div>'

    cats = r.get("categories") or {}
    cat_sorted = sorted(cats.items(), key=lambda kv: kv[1], reverse=True)
    cat_labels = [k for k, _ in cat_sorted]
    cat_values = [v for _, v in cat_sorted]

    # Exclude fix content from page payload — served via API on demand
    slim_rules = [
        {k: v for k, v in rule.items() if k not in ('fix_bash', 'fix_ansible')}
        for rule in (r.get("rules") or [])
    ]
    rules_payload = json.dumps(slim_rules)

    body = f"""
<div class="breadcrumb">
  <a href="/">← all reports</a>
</div>

<div class="report-header card" style="margin-bottom:16px;">
  <div class="rh-grid">
    <div><div class="rh-label">host</div><div class="rh-value">{host}</div></div>
    <div><div class="rh-label">scan date</div><div class="rh-value">{date}</div></div>
    <div><div class="rh-label">profile</div><div class="rh-value">{profile}</div></div>
    <div><div class="rh-label">score</div><div class="rh-value rh-score">{score}%</div></div>
    <div><div class="rh-label">source</div><div class="rh-value mono small">{source}</div></div>
    <div><div class="rh-label">loaded at</div><div class="rh-value mono small">{loaded_at}</div></div>
  </div>
</div>

<div class="metrics" id="metrics"></div>

<div class="grid-2">
  <div class="card">
    <div class="card-title">result distribution</div>
    <div class="legend" id="donut-legend"></div>
    <div style="position:relative;height:200px;">
      <canvas id="donut-chart" role="img" aria-label="Result distribution"></canvas>
    </div>
  </div>
  <div class="card">
    <div class="card-title">failures by category</div>
    <div style="position:relative;" id="bar-wrap">
      <canvas id="bar-chart" role="img" aria-label="Failures by category"></canvas>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-title">failed rules</div>
  {trunc_notice}
  <div class="filter-row">
    <input id="text-filter" type="text" placeholder="filter by id, title, or description..." />
    <div class="filters" id="filters"></div>
    <button id="mark-all-btn" class="mark-btn" onclick="markAllVisible()">Mark all</button>
  </div>
  <div style="overflow-x:auto;">
    <table class="rules-table">
      <thead>
        <tr>
          <th class="check-th"></th>
          <th>Rule</th>
          <th>Category</th>
          <th>Severity</th>
        </tr>
      </thead>
      <tbody id="rules-tbody"></tbody>
    </table>
  </div>
</div>

<div id="correction-bar">
  <span id="selected-count"></span>
  <div class="corr-actions">
    <button class="corr-btn" onclick="downloadCorrection('bash')">&#8595;&nbsp;Bash (.sh)</button>
    <div class="split-group">
      <button class="corr-btn split-main" onclick="downloadCorrection('ansible')">&#8595;&nbsp;Ansible (.yml)</button>
      <button class="corr-btn split-arrow" onclick="toggleAnsibleMenu(event)" title="More options">&#9662;</button>
      <div class="split-menu" id="ansible-split-menu">
        <button onclick="downloadCorrection('ansible');closeAnsibleMenu()">&#8595;&nbsp;Download (.yml)</button>
        <button onclick="showExecModal()">&#9654;&nbsp;Execute on target&hellip;</button>
      </div>
    </div>
  </div>
</div>

<!-- Confirmation modal -->
<div id="exec-overlay" onclick="closeExecModal()" style="display:none;position:fixed;inset:0;background:rgba(0,0,0,0.72);z-index:300;"></div>
<div id="exec-modal" style="display:none;position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);z-index:301;
  background:var(--surface);border:1px solid var(--warn);border-radius:8px;padding:28px 28px 20px;
  max-width:480px;width:92%;font-family:var(--font-mono);">
  <div style="color:var(--warn);font-size:14px;font-weight:500;margin-bottom:14px;">&#9888;&nbsp;Execute Ansible Remediation</div>
  <div id="exec-not-ssh-notice" style="display:none;font-size:12px;color:#fca5a5;background:rgba(239,68,68,0.08);
    border:1px solid rgba(239,68,68,0.3);border-radius:4px;padding:10px 12px;margin-bottom:14px;">
    This report was not collected via SSH. Execute is only available for reports collected via the <strong>Scan</strong> tab.
  </div>
  <p style="font-size:12px;color:var(--text);line-height:1.7;margin-bottom:12px;">
    This will run the selected Ansible tasks <strong>directly on the target server</strong> via SSH.
  </p>
  <ul style="font-size:11px;color:#fcd34d;margin:0 0 18px 18px;line-height:2;">
    <li>Not recommended in production environments</li>
    <li>Some changes may be irreversible</li>
    <li>Services may restart or behave unexpectedly</li>
    <li>Ensure you have tested in a staging environment first</li>
  </ul>
  <div style="display:flex;gap:8px;justify-content:flex-end;">
    <button onclick="closeExecModal()" class="exec-cancel-btn">Cancel</button>
    <button id="exec-confirm-btn" onclick="confirmExec()" class="exec-confirm-btn">I understand &mdash; Execute</button>
  </div>
</div>

<!-- Execution result modal -->
<div id="result-overlay" onclick="closeResultModal()" style="display:none;position:fixed;inset:0;background:rgba(0,0,0,0.72);z-index:300;"></div>
<div id="result-modal" style="display:none;position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);z-index:301;
  background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:24px;
  max-width:720px;width:95%;font-family:var(--font-mono);">
  <div id="result-title" style="font-size:13px;font-weight:500;margin-bottom:14px;color:var(--text);"></div>
  <pre id="result-output" style="font-size:11px;color:var(--text);background:var(--surface2);padding:14px;
    border-radius:4px;overflow-x:auto;white-space:pre-wrap;max-height:52vh;overflow-y:auto;
    border:1px solid var(--border);margin:0;"></pre>
  <div style="margin-top:14px;text-align:right;">
    <button onclick="closeResultModal()" class="exec-cancel-btn">Close</button>
  </div>
</div>

<style>
.breadcrumb {{ font-family: var(--font-mono); font-size: 12px; margin-bottom: 12px; }}
.breadcrumb a {{ color: var(--muted); text-decoration: none; }}
.breadcrumb a:hover {{ color: var(--accent); }}

.rh-grid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; }}
.rh-label {{ font-family: var(--font-mono); font-size: 10px; color: var(--muted); text-transform: uppercase; letter-spacing: .08em; margin-bottom: 4px; }}
.rh-value {{ font-size: 14px; word-break: break-all; }}
.rh-value.mono.small {{ font-family: var(--font-mono); font-size: 11px; color: var(--muted); }}
.rh-score {{ font-family: var(--font-mono); font-size: 22px; font-weight: 300; color: var(--accent); }}

.metrics {{ display: grid; grid-template-columns: repeat(5, 1fr); gap: 12px; margin-bottom: 16px; }}
.metric-card {{ background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 16px; }}
.metric-label {{ font-size: 11px; color: var(--muted); font-family: var(--font-mono); text-transform: uppercase; letter-spacing: .06em; margin-bottom: 8px; }}
.metric-value {{ font-size: 28px; font-weight: 300; font-family: var(--font-mono); line-height: 1; }}
.metric-sub {{ font-size: 11px; color: var(--muted); margin-top: 5px; font-family: var(--font-mono); }}
.metric-value.pass {{ color: var(--pass); }}
.metric-value.fail {{ color: var(--fail); }}
.metric-value.score {{ color: var(--accent); }}
.metric-value.warn {{ color: var(--warn); }}
.metric-value.info {{ color: var(--info); }}

.score-bar-wrap {{ margin-top: 8px; }}
.score-bar-bg {{ height: 3px; background: var(--surface2); border-radius: 2px; }}
.score-bar-fill {{ height: 3px; border-radius: 2px; background: var(--accent); transition: width 1s ease; }}

.grid-2 {{ display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 16px; }}

.legend {{ display: flex; flex-wrap: wrap; gap: 14px; margin-bottom: 12px; }}
.legend-item {{ display: flex; align-items: center; gap: 5px; font-size: 12px; color: var(--muted); font-family: var(--font-mono); }}
.legend-dot {{ width: 8px; height: 8px; border-radius: 2px; flex-shrink: 0; }}

.filter-row {{ display: flex; gap: 12px; align-items: center; flex-wrap: wrap; margin-bottom: 14px; }}
.filters {{ display: flex; gap: 6px; flex-wrap: wrap; }}
.filter-btn {{ font-family: var(--font-mono); font-size: 11px; padding: 4px 10px; border-radius: 4px; border: 1px solid var(--border2); background: transparent; color: var(--muted); cursor: pointer; transition: all .15s; }}
.filter-btn:hover {{ border-color: var(--accent); color: var(--text); }}
.filter-btn.active {{ background: rgba(0,212,255,0.1); border-color: var(--accent); color: var(--accent); }}

.mark-btn {{
  font-family: var(--font-mono); font-size: 11px; padding: 4px 10px; border-radius: 4px;
  border: 1px solid rgba(139,92,246,0.4); background: rgba(139,92,246,0.08);
  color: #c4b5fd; cursor: pointer; transition: all .15s; margin-left: 4px;
}}
.mark-btn:hover {{ border-color: rgba(139,92,246,0.7); background: rgba(139,92,246,0.15); }}

#text-filter {{
  flex: 1; min-width: 200px;
  background: var(--surface2); border: 1px solid var(--border2);
  color: var(--text); padding: 6px 10px; border-radius: 4px;
  font-family: var(--font-mono); font-size: 12px;
}}
#text-filter:focus {{ outline: none; border-color: var(--accent); }}

.rules-table {{ width: 100%; border-collapse: collapse; }}
.check-th {{ width: 36px; }}
.rules-table th {{ font-family: var(--font-mono); font-size: 10px; text-transform: uppercase; letter-spacing: .08em; color: var(--muted); padding: 8px 10px; border-bottom: 1px solid var(--border); text-align: left; font-weight: 400; }}
.rules-table td {{ padding: 10px 10px; border-bottom: 1px solid var(--border); vertical-align: middle; }}
.rules-table tr:last-child td {{ border-bottom: none; }}
.rules-table tr:hover td {{ background: rgba(255,255,255,0.02); }}
.rule-title-text {{ font-size: 13px; line-height: 1.4; font-weight: 500; }}
.rule-desc {{ font-size: 12px; line-height: 1.5; color: #9ca3af; margin-top: 4px; }}
.rule-id {{ font-family: var(--font-mono); font-size: 10px; color: var(--muted); margin-top: 4px; word-break: break-all; }}

.check-cell {{ width: 36px; text-align: center; vertical-align: middle !important; }}
.rule-check {{ width: 14px; height: 14px; cursor: pointer; accent-color: var(--accent); }}

.badge {{ font-family: var(--font-mono); font-size: 10px; padding: 2px 7px; border-radius: 3px; border: 1px solid; white-space: nowrap; display: inline-block; }}
.badge-high {{ color: #fca5a5; border-color: rgba(239,68,68,0.3); background: rgba(239,68,68,0.08); }}
.badge-medium {{ color: #fcd34d; border-color: rgba(245,158,11,0.3); background: rgba(245,158,11,0.08); }}
.badge-low {{ color: #93c5fd; border-color: rgba(59,130,246,0.3); background: rgba(59,130,246,0.08); }}
.badge-cat {{ color: var(--muted); border-color: var(--border2); background: transparent; }}

.trunc-notice {{ font-family: var(--font-mono); font-size: 11px; color: var(--warn); margin-bottom: 10px; }}

/* Correction bar */
#correction-bar {{
  display: none;
  position: fixed; bottom: 0; left: 0; right: 0; z-index: 200;
  background: var(--surface);
  border-top: 1px solid var(--accent);
  padding: 12px 32px;
  align-items: center;
  justify-content: space-between;
  font-family: var(--font-mono); font-size: 12px;
  box-shadow: 0 -4px 24px rgba(0,212,255,0.08);
}}
#selected-count {{ color: var(--accent); font-size: 13px; }}
.corr-actions {{ display: flex; gap: 8px; }}
.corr-btn {{
  font-family: var(--font-mono); font-size: 12px;
  background: rgba(0,212,255,0.1); border: 1px solid var(--accent);
  color: var(--accent); padding: 7px 16px; border-radius: 4px; cursor: pointer;
  transition: background .15s;
}}
.corr-btn:hover {{ background: rgba(0,212,255,0.22); }}

.split-group {{ position: relative; display: flex; }}
.split-main {{ border-radius: 4px 0 0 4px !important; border-right-color: rgba(0,212,255,0.25) !important; }}
.split-arrow {{ border-radius: 0 4px 4px 0 !important; padding: 7px 10px !important; border-left: none !important; }}
.split-arrow:hover {{ background: rgba(0,212,255,0.22); }}
.split-menu {{
  display: none; position: absolute; bottom: calc(100% + 6px); right: 0;
  background: var(--surface); border: 1px solid var(--border2);
  border-radius: 6px; min-width: 190px; overflow: hidden;
  box-shadow: 0 6px 24px rgba(0,0,0,0.5); z-index: 250;
}}
.split-menu button {{
  display: block; width: 100%; text-align: left;
  padding: 10px 16px; font-family: var(--font-mono); font-size: 12px;
  background: transparent; border: none; color: var(--text); cursor: pointer;
  transition: background .12s;
}}
.split-menu button:hover {{ background: var(--surface2); }}
.split-menu button:first-child {{ border-bottom: 1px solid var(--border); }}

.exec-cancel-btn {{
  font-family: var(--font-mono); font-size: 12px; padding: 7px 16px;
  border-radius: 4px; border: 1px solid var(--border2); background: transparent;
  color: var(--muted); cursor: pointer; transition: all .15s;
}}
.exec-cancel-btn:hover {{ border-color: var(--accent); color: var(--text); }}
.exec-confirm-btn {{
  font-family: var(--font-mono); font-size: 12px; padding: 7px 16px;
  border-radius: 4px; border: 1px solid var(--warn);
  background: rgba(245,158,11,0.1); color: var(--warn); cursor: pointer;
  transition: all .15s;
}}
.exec-confirm-btn:hover {{ background: rgba(245,158,11,0.2); }}
</style>

<script>
const REPORT = {{
  id: {json.dumps(report_id)},
  source: {json.dumps(r.get("source", ""))},
  pass: {pass_n}, fail: {fail_n}, nc: {nc_n}, na: {na_n}, total: {total},
  score: {score}, profile: {json.dumps(r.get("profile", "") or "")},
  filename: {json.dumps(r.get("filename", ""))},
  rules: {rules_payload},
  catLabels: {json.dumps(cat_labels)},
  catValues: {json.dumps(cat_values)}
}};

let activeSev = 'all';
const selectedRuleIds = new Set();

(function render() {{
  document.getElementById('metrics').innerHTML = `
    <div class="metric-card">
      <div class="metric-label">Score</div>
      <div class="metric-value score">${{REPORT.score}}%</div>
      <div class="score-bar-wrap"><div class="score-bar-bg"><div class="score-bar-fill" style="width:${{REPORT.score}}%"></div></div></div>
      <div class="metric-sub">${{REPORT.profile ? (REPORT.profile.split('_profile_')[1] || 'profile') : 'n/a'}}</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">Total rules</div>
      <div class="metric-value info">${{REPORT.total}}</div>
      <div class="metric-sub">${{REPORT.filename}}</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">Pass</div>
      <div class="metric-value pass">${{REPORT.pass}}</div>
      <div class="metric-sub">${{Math.round(REPORT.pass/REPORT.total*100)}}% of rules</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">Fail</div>
      <div class="metric-value fail">${{REPORT.fail}}</div>
      <div class="metric-sub">${{Math.round(REPORT.fail/REPORT.total*100)}}% of rules</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">Not checked</div>
      <div class="metric-value warn">${{REPORT.nc}}</div>
      <div class="metric-sub">+ ${{REPORT.na}} not applicable</div>
    </div>`;

  const donut = {{
    labels: ['Pass', 'Fail', 'Not checked', 'Not applicable'],
    values: [REPORT.pass, REPORT.fail, REPORT.nc, REPORT.na],
    colors: ['#22c55e','#ef4444','#8b5cf6','#6b7280']
  }};
  document.getElementById('donut-legend').innerHTML = donut.labels.map((l,i) =>
    `<div class="legend-item"><div class="legend-dot" style="background:${{donut.colors[i]}}"></div>${{l}} <strong style="color:var(--text)">${{donut.values[i]}}</strong></div>`
  ).join('');
  new Chart(document.getElementById('donut-chart'), {{
    type: 'doughnut',
    data: {{ labels: donut.labels, datasets: [{{ data: donut.values, backgroundColor: donut.colors, borderWidth: 0, hoverOffset: 4 }}] }},
    options: {{ responsive: true, maintainAspectRatio: false, cutout: '70%',
      plugins: {{ legend: {{ display: false }}, tooltip: {{ callbacks: {{ label: c => ` ${{c.label}}: ${{c.parsed}}` }} }} }}
    }}
  }});

  const barH = Math.max(160, REPORT.catLabels.length * 36 + 40);
  document.getElementById('bar-wrap').style.height = barH + 'px';
  new Chart(document.getElementById('bar-chart'), {{
    type: 'bar',
    data: {{ labels: REPORT.catLabels, datasets: [{{ data: REPORT.catValues, backgroundColor: '#ef4444', borderRadius: 3, borderSkipped: false }}] }},
    options: {{ responsive: true, maintainAspectRatio: false, indexAxis: 'y',
      plugins: {{ legend: {{ display: false }}, tooltip: {{ callbacks: {{ label: c => ` ${{c.parsed}} failures` }} }} }},
      scales: {{
        x: {{ grid: {{ color: 'rgba(255,255,255,0.04)' }}, ticks: {{ color: '#6b7280', font: {{ family: "'IBM Plex Mono'" }} }} }},
        y: {{ grid: {{ display: false }}, ticks: {{ color: '#9ca3af', font: {{ family: "'IBM Plex Mono'", size: 11 }} }} }}
      }}
    }}
  }});

  renderFilters();
  applyFilters();
  document.getElementById('text-filter').addEventListener('input', applyFilters);
}})();

function renderFilters() {{
  const high = REPORT.rules.filter(r => r.severity === 'high').length;
  const med  = REPORT.rules.filter(r => r.severity === 'medium').length;
  const low  = REPORT.rules.filter(r => r.severity === 'low').length;
  document.getElementById('filters').innerHTML = `
    <button class="filter-btn active" data-sev="all">All (${{REPORT.rules.length}})</button>
    <button class="filter-btn" data-sev="high">&#9650; High (${{high}})</button>
    <button class="filter-btn" data-sev="medium">&#9632; Medium (${{med}})</button>
    <button class="filter-btn" data-sev="low">&#9660; Low (${{low}})</button>`;
  document.querySelectorAll('.filter-btn').forEach(b => {{
    b.addEventListener('click', () => {{
      document.querySelectorAll('.filter-btn').forEach(x => x.classList.remove('active'));
      b.classList.add('active');
      activeSev = b.dataset.sev;
      applyFilters();
    }});
  }});
}}

function applyFilters() {{
  const text = (document.getElementById('text-filter').value || '').toLowerCase();
  const tbody = document.getElementById('rules-tbody');
  const filtered = REPORT.rules.filter(r => {{
    if (activeSev !== 'all' && r.severity !== activeSev) return false;
    if (text) {{
      const hay = ((r.id || '') + ' ' + (r.title || '') + ' ' + (r.description || '')).toLowerCase();
      if (!hay.includes(text)) return false;
    }}
    return true;
  }});
  if (!filtered.length) {{
    tbody.innerHTML = '<tr><td colspan="4"><div class="empty-state">no rules match</div></td></tr>';
    updateMarkBtn(0, 0);
    return;
  }}
  tbody.innerHTML = filtered.map(r => `
    <tr>
      <td class="check-cell">
        <input type="checkbox" class="rule-check" value="${{escapeHtml(r.id)}}"
               ${{selectedRuleIds.has(r.id) ? 'checked' : ''}}
               onchange="onCheckChange(this)">
      </td>
      <td>
        <div class="rule-title-text">${{escapeHtml(r.title)}}</div>
        ${{r.description ? `<div class="rule-desc">${{escapeHtml(r.description)}}</div>` : ''}}
        <div class="rule-id">${{escapeHtml(r.id)}}</div>
      </td>
      <td><span class="badge badge-cat">${{escapeHtml(r.category)}}</span></td>
      <td><span class="badge badge-${{r.severity}}">${{r.severity === 'high' ? '&#9650; High' : r.severity === 'medium' ? '&#9632; Medium' : '&#9660; Low'}}</span></td>
    </tr>`).join('');

  const checks = document.querySelectorAll('.rule-check');
  const checkedCount = Array.from(checks).filter(c => c.checked).length;
  updateMarkBtn(checkedCount, checks.length);
}}

function onCheckChange(cb) {{
  if (cb.checked) selectedRuleIds.add(cb.value);
  else selectedRuleIds.delete(cb.value);
  const checks = document.querySelectorAll('.rule-check');
  const checkedCount = Array.from(checks).filter(c => c.checked).length;
  updateMarkBtn(checkedCount, checks.length);
  updateCorrectionBar();
}}

function updateMarkBtn(checkedVisible, totalVisible) {{
  const btn = document.getElementById('mark-all-btn');
  if (!btn) return;
  if (totalVisible === 0) {{
    btn.textContent = 'Mark all';
    return;
  }}
  if (checkedVisible === totalVisible) {{
    btn.textContent = `Unmark all (${{totalVisible}})`;
  }} else {{
    btn.textContent = `Mark all (${{totalVisible - checkedVisible}})`;
  }}
}}

function markAllVisible() {{
  const checks = document.querySelectorAll('.rule-check');
  const allChecked = Array.from(checks).every(c => c.checked);
  checks.forEach(cb => {{
    cb.checked = !allChecked;
    if (!allChecked) selectedRuleIds.add(cb.value);
    else selectedRuleIds.delete(cb.value);
  }});
  updateMarkBtn(allChecked ? 0 : checks.length, checks.length);
  updateCorrectionBar();
}}

function updateCorrectionBar() {{
  const n = selectedRuleIds.size;
  const bar = document.getElementById('correction-bar');
  const main = document.querySelector('main');
  if (n > 0) {{
    bar.style.display = 'flex';
    main.style.paddingBottom = '68px';
    document.getElementById('selected-count').textContent =
      n + ' rule' + (n !== 1 ? 's' : '') + ' selected';
  }} else {{
    bar.style.display = 'none';
    main.style.paddingBottom = '';
  }}
}}

function downloadCorrection(format) {{
  const ids = Array.from(selectedRuleIds);
  if (!ids.length) return;
  fetch('/api/report/' + encodeURIComponent(REPORT.id) + '/correction', {{
    method: 'POST',
    headers: {{'Content-Type': 'application/json'}},
    body: JSON.stringify({{format: format, rules: ids}})
  }})
  .then(resp => {{
    if (!resp.ok) throw new Error('Server error ' + resp.status);
    const cd = resp.headers.get('Content-Disposition') || '';
    const m = cd.match(/filename="([^"]+)"/);
    const filename = m ? m[1] : ('remediation.' + (format === 'bash' ? 'sh' : 'yml'));
    return resp.blob().then(blob => ({{blob, filename}}));
  }})
  .then(({{blob, filename}}) => {{
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = filename;
    document.body.appendChild(a); a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }})
  .catch(err => alert('Download failed: ' + err.message));
}}

// ---- Split button / Ansible menu ----
function toggleAnsibleMenu(e) {{
  e.stopPropagation();
  const menu = document.getElementById('ansible-split-menu');
  menu.style.display = menu.style.display === 'block' ? 'none' : 'block';
}}
function closeAnsibleMenu() {{
  const m = document.getElementById('ansible-split-menu');
  if (m) m.style.display = 'none';
}}
document.addEventListener('click', closeAnsibleMenu);

// ---- Execution modals ----
function showExecModal() {{
  closeAnsibleMenu();
  const notSsh = !REPORT.source || !REPORT.source.startsWith('ssh:');
  const notice = document.getElementById('exec-not-ssh-notice');
  const confirmBtn = document.getElementById('exec-confirm-btn');
  if (notice) notice.style.display = notSsh ? 'block' : 'none';
  if (confirmBtn) confirmBtn.style.display = notSsh ? 'none' : 'inline-block';
  document.getElementById('exec-overlay').style.display = 'block';
  document.getElementById('exec-modal').style.display = 'block';
}}
function closeExecModal() {{
  document.getElementById('exec-overlay').style.display = 'none';
  document.getElementById('exec-modal').style.display = 'none';
}}

function confirmExec() {{
  closeExecModal();
  const ids = Array.from(selectedRuleIds);
  if (!ids.length) return;

  // Open result modal in loading state
  document.getElementById('result-title').textContent = 'Executing Ansible remediation…';
  document.getElementById('result-output').textContent = 'Connecting to target and running playbook. This may take several minutes depending on the number of rules.';
  document.getElementById('result-overlay').style.display = 'block';
  document.getElementById('result-modal').style.display = 'block';

  fetch('/api/report/' + encodeURIComponent(REPORT.id) + '/correction/execute', {{
    method: 'POST',
    headers: {{'Content-Type': 'application/json'}},
    body: JSON.stringify({{format: 'ansible', rules: ids}})
  }})
  .then(resp => resp.json())
  .then(data => {{
    if (data.error) {{
      document.getElementById('result-title').innerHTML =
        '<span style="color:#fca5a5">&#10060; Execution error</span>';
      document.getElementById('result-output').textContent = data.error;
    }} else {{
      const stdout = data.stdout || '';
      // Parse PLAY RECAP for summary
      const recapMatch = stdout.match(/localhost\\s*:\\s*(ok=\\d+\\s+changed=\\d+[^\\n]*)/);
      const recap = recapMatch ? recapMatch[1].trim() : null;
      const changedMatch = recap && recap.match(/changed=(\\d+)/);
      const rescuedMatch = recap && recap.match(/rescued=(\\d+)/);
      const changed = changedMatch ? parseInt(changedMatch[1]) : -1;
      const rescued = rescuedMatch ? parseInt(rescuedMatch[1]) : 0;

      let titleHtml = '';
      if (data.exit_code === 0 && changed === 0) {{
        titleHtml = '<span style="color:var(--warn)">&#9888; Ansible completed &mdash; no changes applied (changed=0)</span>';
      }} else if (data.exit_code === 0 && changed > 0) {{
        titleHtml = '<span style="color:#86efac">&#10003; Ansible completed &mdash; ' + changed + ' change(s) applied</span>';
      }} else {{
        titleHtml = '<span style="color:#fca5a5">&#10060; Ansible finished with errors (exit code: ' + data.exit_code + ')</span>';
      }}
      if (recap) {{
        titleHtml += '<div style="font-size:11px;color:var(--muted);margin-top:6px;font-family:var(--font-mono);">' + escapeHtml(recap) + '</div>';
        if (rescued > 0) {{
          titleHtml += '<div style="font-size:11px;color:#fcd34d;margin-top:4px;">&#9888; ' + rescued + ' rule(s) skipped due to pre-conditions — see output for details.</div>';
        }}
      }}
      document.getElementById('result-title').innerHTML = titleHtml;

      const nl = String.fromCharCode(10);
      const combined = [stdout, data.stderr ? '--- stderr ---' + nl + data.stderr : ''].filter(Boolean).join(nl + nl);
      document.getElementById('result-output').textContent = combined || '(no output)';
    }}
  }})
  .catch(err => {{
    document.getElementById('result-title').textContent = '❌ Request failed';
    document.getElementById('result-output').textContent = err.message;
    document.getElementById('result-output').style.color = '#fca5a5';
  }});
}}
function closeResultModal() {{
  document.getElementById('result-overlay').style.display = 'none';
  document.getElementById('result-modal').style.display = 'none';
}}

function escapeHtml(s) {{
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}}
</script>
"""
    title = f"{r.get('hostname', 'unknown')} — OpenSCAP Dashboard"
    return base_html(title, body, active="index")


@bp.route("/report/<rid>", methods=["GET"])
def report_view(rid: str):
    r = store.get(rid)
    if r is None:
        return _not_found_html(rid), 404
    return _report_html(r)


@bp.route("/api/report/<rid>", methods=["GET"])
def api_report(rid: str):
    r = store.get(rid)
    if r is None:
        abort(404)
    return jsonify(r)


@bp.route("/api/report/<rid>/correction/execute", methods=["POST"])
def execute_correction(rid: str):
    from app import scanner as scanner_mod
    from app import targets as targets_mod

    r = store.get(rid)
    if r is None:
        abort(404)

    data = request.get_json(silent=True) or {}
    fmt = (data.get("format") or "ansible").lower()
    rule_ids = set(data.get("rules") or [])
    if not rule_ids:
        return jsonify({"error": "No rules selected."}), 400

    source = r.get("source", "")
    if not source.startswith("ssh:"):
        return jsonify({"error": "Execute is only available for reports collected via SSH scan."}), 400

    host = source.replace("ssh:", "").strip()
    target = next((t for t in targets_mod.all_targets() if t["host"] == host), None)
    if target is None:
        return jsonify({
            "error": f"No SSH target configured for '{host}'. Add it in the Scan tab first."
        }), 400

    selected = [rule for rule in (r.get("rules") or []) if rule.get("id") in rule_ids]
    ts = int(_time.time())

    if fmt == "ansible":
        content = _generate_ansible(selected, r)
        remote_path = f"/tmp/_oscap_remediation_{ts}.yml"
        exec_cmd = f"ansible-playbook -i 'localhost,' -c local '{remote_path}' 2>&1"
    else:
        content = _generate_bash(selected, r)
        remote_path = f"/tmp/_oscap_remediation_{ts}.sh"
        exec_cmd = f"bash '{remote_path}' 2>&1"

    try:
        client = scanner_mod._connect(target)
        with client.open_sftp() as sftp:
            with sftp.file(remote_path, "w") as fobj:
                fobj.write(content)
            sftp.chmod(remote_path, 0o700)

        rc, stdout, stderr = scanner_mod._exec(client, exec_cmd, timeout=300)
        scanner_mod._exec(client, f"rm -f '{remote_path}'", timeout=10)
        client.close()

        return jsonify({
            "exit_code": rc,
            "stdout": stdout,
            "stderr": stderr,
            "success": rc == 0,
        })
    except Exception as exc:
        return jsonify({"error": str(exc)}), 500


@bp.route("/api/report/<rid>/correction", methods=["POST"])
def download_correction(rid: str):
    r = store.get(rid)
    if r is None:
        abort(404)

    data = request.get_json(silent=True) or {}
    fmt = (data.get("format") or "bash").lower()
    rule_ids = set(data.get("rules") or [])
    if not rule_ids:
        abort(400)

    selected = [rule for rule in (r.get("rules") or []) if rule.get("id") in rule_ids]

    hostname = r.get("hostname", "host")
    if fmt == "ansible":
        content = _generate_ansible(selected, r)
        filename = f"oscap-remediation-{hostname}.yml"
        mime = "text/yaml"
    else:
        content = _generate_bash(selected, r)
        filename = f"oscap-remediation-{hostname}.sh"
        mime = "text/x-sh"

    return Response(
        content,
        mimetype=mime,
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
